# 应用服务 WEB 访问端口
server:
  port: 8105
  servlet:
    context-path: /api

# 应用服务名称
spring:
  application:
    name: oj-code-sandbox

# 调用docker服务（本项目使用本地docker，由于要挂载数据卷，只能在本地）
docker:
  host: tcp://127.0.0.1:2375
  api-version: 1.47

auth:
  request:
    header: auth
    secret: secretkey

